apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressroute.name }}
  namespace: {{ .Values.cert.namespace }}
spec:
  entryPoints:
  - web
  - websecure
  - hvg
  - myport
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.host }}`)
    services:
    - name: {{ include "hello-kubernetes.name" . }}
      port: 3031
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.host }}`)
    services:
    - name: {{ include "hello-kubernetes.name" . }}
      port: 3030
  tls:
    secretName: {{ .Values.cert.secretname }}
