apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressroute.name }}
  namespace: {{ .Values.cert.namespace }}
spec:
  entryPoints:
  - web
  - websecure
  - hvg
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.host }}`)
    services:
    - name: {{ include "hello-kubernetes.name" . }}
      port: 3031
#     - name: {{ include "hello-kubernetes.name" . }}
#       port: https
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.host }}`)
    services:
    - name: {{ include "hello-kubernetes.name" . }}
      port: https
#   - kind: Rule
#     match: Host(`{{ .Values.ingressroute.host }}`) && PathPrefix(`/apple`)
#     services:
#     - name: apple-service
#       port: 3031
#   - kind: Rule
#     match: Host(`{{ .Values.ingressroute.host }}`) && PathPrefix(`/banana`)
#     services:
#     - name: banana-service
#       port: own
  tls:
    secretName: {{ .Values.cert.secretname }}
