---
apiVersion: v1
kind: Pod
metadata:
  name: apple-app
  labels:
    app: apple
  namespace: app
spec:
  containers:
  - name: apple-app
    image: public.ecr.aws/l0z3e7h5/test:latest
    args:
        - "-text=apple"
