apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  name: {{ include "hello-kubernetes.name" . }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-kubernetes.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-hello-world
  name: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-hello-world
    spec:
      containers:
      - image: us.icr.io/samples/node-hello-world:v1
        name: node-hello-world
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-hello-world
  name: node-hello-world
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-hello-world
  type: LoadBalancer
status:
  loadBalancer: {}
