apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  name: {{ include "hello-kubernetes.name" . }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3031
      targetPort: http
      protocol: TCP
      name: http
    - port: 3032
      targetPort: http
      protocol: TCP
      name: http3032
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  selector:
    {{- include "hello-kubernetes.selectorLabels" . | nindent 4 }}
