# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: LoadBalancer
  port: 3030
cert:
  name: hvgnewapp.newcross-sbx.com
  namespace: app
  secretname: hvgnewapp.newcross-sbx.com
  dnsname: hvgnewapp.newcross-sbx.com

ingressroute:
  name: ingressRoute
  host: hvgnewapp.newcross-sbx.com

deployment:
  replicaCount: 2
  container:
    image:
      repository: "paulbouwer/hello-kubernetes"
      tag: "" # uses chart appVersion if not provided
      pullPolicy: IfNotPresent
    port: 3031

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

